apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - service-canary.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - rollback-cronjob.yaml
