apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: credit-risk-api
  namespace: credit-risk
spec:
  podSelector:
    matchLabels:
      app: credit-risk-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
